DROP TABLE f_article CASCADE;
CREATE TABLE f_article
(
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  audit     VARCHAR(40),
  tags      VARCHAR(120),
  title     INT(3),
  issueDate DATETIME,
  summary   VARCHAR(120),
  content   TEXT,
  PRIMARY KEY (id)
);